# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\AnacodaProject\-Taichung-City-Bus-Transfer-(PyQt_GUI)\helloBusDailog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_HelloBus(object):
    def setupUi(self, Dialog_HelloBus):
        Dialog_HelloBus.setObjectName("Dialog_HelloBus")
        Dialog_HelloBus.resize(520, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_HelloBus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_HelloBusPicture = QtWidgets.QLabel(Dialog_HelloBus)
        self.label_HelloBusPicture.setText("")
        self.label_HelloBusPicture.setPixmap(QtGui.QPixmap(":/helloBus/中興幹線.png"))
        self.label_HelloBusPicture.setObjectName("label_HelloBusPicture")
        self.verticalLayout.addWidget(self.label_HelloBusPicture)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_HelloBus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_HelloBus)
        self.buttonBox.accepted.connect(Dialog_HelloBus.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_HelloBus.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_HelloBus)

    def retranslateUi(self, Dialog_HelloBus):
        _translate = QtCore.QCoreApplication.translate
        Dialog_HelloBus.setWindowTitle(_translate("Dialog_HelloBus", "哈囉你好嗎？"))
import Resource.helloBus_rc
